"""tornar classificacao indicativa opcional

Revision ID: 2aa15acb8eb7
Revises: c30d7fec34c0
Create Date: 2026-09-25 12:35:34.828302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2aa15acb8eb7"
down_revision: str | Sequence[str] | None = "c30d7fec34c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("obras", "classificacao_indicativa", existing_type=sa.SMALLINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Falha se existirem obras sem classificação; atribua um valor a elas antes de reverter.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "obras", "classificacao_indicativa", existing_type=sa.SMALLINT(), nullable=False
    )
    # ### end Alembic commands ###
