"""criar tabelas iniciais

Revision ID: c30d7fec34c0
Revises:
Create Date: 2026-09-24 19:33:26.586147

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c30d7fec34c0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generos")),
        sa.UniqueConstraint("nome", name=op.f("uq_generos_nome")),
    )
    op.create_table(
        "obras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("filme", "serie", name="tipo_obra", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("ano_lancamento", sa.SmallInteger(), nullable=False),
        sa.Column("sinopse", sa.Text(), nullable=True),
        sa.Column("classificacao_indicativa", sa.SmallInteger(), nullable=False),
        sa.Column("duracao_minutos", sa.SmallInteger(), nullable=True),
        sa.Column("temporadas", sa.SmallInteger(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(tipo = 'filme' AND duracao_minutos IS NOT NULL AND temporadas IS NULL) OR (tipo = 'serie' AND temporadas IS NOT NULL AND duracao_minutos IS NULL)",
            name=op.f("ck_obras_duracao_conforme_tipo"),
        ),
        sa.CheckConstraint("ano_lancamento >= 1888", name=op.f("ck_obras_ano_lancamento_valido")),
        sa.CheckConstraint(
            "classificacao_indicativa IN (0, 10, 12, 14, 16, 18)",
            name=op.f("ck_obras_classificacao_indicativa_valida"),
        ),
        sa.CheckConstraint("duracao_minutos > 0", name=op.f("ck_obras_duracao_minutos_positiva")),
        sa.CheckConstraint("temporadas > 0", name=op.f("ck_obras_temporadas_positiva")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_obras")),
    )
    op.create_index(op.f("ix_obras_ano_lancamento"), "obras", ["ano_lancamento"], unique=False)
    op.create_index(op.f("ix_obras_tipo"), "obras", ["tipo"], unique=False)
    op.create_index(op.f("ix_obras_titulo"), "obras", ["titulo"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "papel",
            sa.Enum(
                "admin", "usuario", name="papel_usuario", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("email", name=op.f("uq_usuarios_email")),
    )
    op.create_table(
        "avaliacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("nota", sa.SmallInteger(), nullable=False),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("nota BETWEEN 1 AND 5", name=op.f("ck_avaliacoes_nota_valida")),
        sa.ForeignKeyConstraint(
            ["obra_id"], ["obras.id"], name=op.f("fk_avaliacoes_obra_id_obras"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_avaliacoes_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_avaliacoes")),
        sa.UniqueConstraint("usuario_id", "obra_id", name="uq_avaliacoes_usuario_obra"),
    )
    op.create_index(op.f("ix_avaliacoes_obra_id"), "avaliacoes", ["obra_id"], unique=False)
    op.create_table(
        "itens_lista",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "quero_assistir",
                "assistindo",
                "assistido",
                name="status_lista",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["obra_id"], ["obras.id"], name=op.f("fk_itens_lista_obra_id_obras"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_itens_lista_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itens_lista")),
        sa.UniqueConstraint("usuario_id", "obra_id", name="uq_itens_lista_usuario_obra"),
    )
    op.create_index(op.f("ix_itens_lista_obra_id"), "itens_lista", ["obra_id"], unique=False)
    op.create_index(
        "ix_itens_lista_usuario_status", "itens_lista", ["usuario_id", "status"], unique=False
    )
    op.create_table(
        "obras_generos",
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("genero_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genero_id"],
            ["generos.id"],
            name=op.f("fk_obras_generos_genero_id_generos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["obra_id"],
            ["obras.id"],
            name=op.f("fk_obras_generos_obra_id_obras"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("obra_id", "genero_id", name=op.f("pk_obras_generos")),
    )
    op.create_index("ix_obras_generos_genero_id", "obras_generos", ["genero_id"], unique=False)
    op.create_table(
        "posters",
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("conteudo", sa.LargeBinary(), nullable=False),
        sa.Column("tipo_mime", sa.String(length=20), nullable=False),
        sa.Column("tamanho_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tipo_mime IN ('image/jpeg', 'image/png', 'image/webp')",
            name=op.f("ck_posters_tipo_mime_permitido"),
        ),
        sa.CheckConstraint(
            "tamanho_bytes > 0 AND tamanho_bytes <= 2097152",
            name=op.f("ck_posters_tamanho_permitido"),
        ),
        sa.ForeignKeyConstraint(
            ["obra_id"], ["obras.id"], name=op.f("fk_posters_obra_id_obras"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("obra_id", name=op.f("pk_posters")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posters")
    op.drop_index("ix_obras_generos_genero_id", table_name="obras_generos")
    op.drop_table("obras_generos")
    op.drop_index("ix_itens_lista_usuario_status", table_name="itens_lista")
    op.drop_index(op.f("ix_itens_lista_obra_id"), table_name="itens_lista")
    op.drop_table("itens_lista")
    op.drop_index(op.f("ix_avaliacoes_obra_id"), table_name="avaliacoes")
    op.drop_table("avaliacoes")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_obras_titulo"), table_name="obras")
    op.drop_index(op.f("ix_obras_tipo"), table_name="obras")
    op.drop_index(op.f("ix_obras_ano_lancamento"), table_name="obras")
    op.drop_table("obras")
    op.drop_table("generos")
    # ### end Alembic commands ###
